spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT-ID}
            client-secret: ${CLIENT-SECRET}
            scope: read:public_repo